Realm:
    type: object
    config:
        description: "Common information about the Realm."
        fields:
            name:
                type: "String!"
                description: "The name of this realm."
            configuration:
                type: "Configuration!"
                description: "Information about the software and module installed on this realm."
